#!/usr/bin/env bash

function _export_global_variables() {
    local root
    root="$(cd "$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")" >/dev/null && pwd)"
    source "$root"/neo4j
}


function _commands() {
    function _install_jdk() {
         command -v javac 1>/dev/null 2>&1 || brew install openjdk@11
    }

    function _install_maven() {
         command -v mvn 1>/dev/null 2>&1 || brew install maven
    }

    function _install_poetry() {
        command -v poetry 1>/dev/null 2>&1 || "$ROOT_DIR"/neo4j install_poetry "$ROOT_DIR"/.poetry python3.9
    }

    function _install_python_universal2() {
        if ! [[ $(python3 -c "import sysconfig;print(sysconfig.get_platform())") == *-universal2 ]];then
            wget https://www.python.org/ftp/python/3.9.10/python-3.9.10-macos11.pkg
            sudo installer -pkg python-3.9.10-macos11.pkg -target $HOME
            /Applications/Python\ 3.9/Install\ Certificates.command
            /Applications/Python\ 3.9/Update\ Shell\ Profile.command
            source "$HOME/.bash_profile"
        fi
    }
}

function _main() {
    set -e

    _commands
    _export_global_variables

    _install_jdk
    _install_maven
    _install_python_universal2
    _install_poetry
}

_main
