#!/usr/bin/env bash

function _export_global_variables() {
    local root
    root="$(cd "$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")" >/dev/null && pwd)"
    source "$root"/neo4j
}


function _commands() {
    function _apt_update() {
        sudo apt-get -y update
    }

    function _upgrade_openssl() {
        sudo apt-get install --only-upgrade libssl-dev
    }

    function _install_jdk() {
        command -v javac 1>/dev/null 2>&1 || sudo apt-get -y install openjdk-11-jdk
    }

    function _install_jq() {
        command -v jq 1>/dev/null 2>&1 || sudo apt-get -y install jq
    }

    function _install_maven() {
        command -v mvn 1>/dev/null 2>&1 || sudo apt-get -y install maven
    }

    function _install_python_dev() {
        sudo apt-get -y install python3.9-dev
    }

    function _install_poetry() {
        command -v poetry 1>/dev/null 2>&1 || "$ROOT_DIR"/neo4j install_poetry "$ROOT_DIR"/.poetry /usr/bin/python3.9
    }
}

function _main() {
    set -e

    _commands
    _export_global_variables

    _apt_update
    _upgrade_openssl
    _install_python_dev
    _install_poetry
    _install_jdk
    _install_jq
    _install_maven
}

_main
