[tool.poetry]
name = "neo4j_app"
version = "0.1.0"
description = "neo4j backend for the Datashare extension"
authors = ["ICIJ <engineering@icij.org>"]
# TODO: add readme
packages = [
    { include = "neo4j_app" }
]
exclude = ["neo4j_app/tests"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.89.1"
# PyYaml > 5.3.1 does not seem to be installable on macos 13.x
pyyaml = "<=5.3.1"
uvicorn = { version = "^0.20.0", extras = ["standard"] }
elasticsearch = {version = "^7.17.9", extras = ["async"]}
neo4j = "^5.5.0"

[tool.poetry.group.dev.dependencies]
fastapi = { version = "^0.89.1", extras = ["all"] }
pylint = "^2.15.10"
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
