[tool.poetry]
name = "neo4j_app"
version = "0.1.0rc0"
description = "neo4j backend for the Datashare extension"
authors = ["ICIJ <engineering@icij.org>"]
# TODO: add readme
packages = [
    { include = "neo4j_app" }
]
exclude = ["neo4j_app/tests"]

[tool.black]
line-length = 88
target = "py38"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.89.1"
pyyaml = ">=5.4.0" # For security
uvicorn = { version = "^0.20.0", extras = ["standard"] }
elasticsearch = {version = "<7.14", extras = ["async"]}
neo4j = "^5.5.0"
setuptools = "^67.6.1"
datrie = "^0.8.2"
# We freeze the pika version because exception handling is tightly coupled to that version. When pika exception
# handling will improve, we'll losen the boundaries
pika = "1.3.2"
tenacity = "^8.2.2"

[tool.poetry.group.dev.dependencies]
fastapi = { version = "^0.89.1", extras = ["all"] }
pylint = "^2.15.10"
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
tomli = { version = "^2.0.1", markers = 'python_version < "3.11"' }
aiohttp = "^3.8.4"

[tool.poetry.group.opensearch.dependencies]
opensearch-py = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
