version: 2.1

parameters:
  release_branch:
    description: Trigger branch release
    type: boolean
    default: false
  branch:
    description: >
      Branch to release (the last commit will be used, if a new one occurs during the release, it will probably
      fail...)
    type: string
    default: main

executors:
  docker-machine:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: true
  unknown-linux:
    machine:
      image: ubuntu-2004:2022.04.1
  darwin-universal2:
    macos:
      xcode: 14.2.0

commands:
  build-binary:
    description: Build neo4j_app binary
    parameters:
      branch:
        type: string
    steps:
      - checkout-code:
          revision: << parameters.branch >>
      # TODO: cache apt
      - run:
          name: Setting up environment
          # TODO: remove the source ~/.bashrc is not needed
          # We make a separate cache dir to avoid conflict with docker
          command: |
            cd datashare-extension-neo4j
            ./neo4j setup -p build_env
            echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
            source ~/.bashrc
            echo "export PATH=$CIRCLE_WORKING_DIRECTORY/datashare-extension-neo4j/.poetry/bin:$PATH" >> "$BASH_ENV"
            source "$BASH_ENV"
            mkdir $CIRCLE_WORKING_DIRECTORY/datashare-extension-neo4j/.cache
            poetry config cache-dir $CIRCLE_WORKING_DIRECTORY/datashare-extension-neo4j/.cache
      # This has to be done after installing poetry
      - run:
          name: Perform sanity checks
          command: |
            cd datashare-extension-neo4j
            ./neo4j is_publishable
      # Fail early
      - check-is-latest-commit:
          branch: << parameters.branch >>
      - run:
          name: Build binary
          command: |
            cd datashare-extension-neo4j
            ./neo4j setup -p neo4j_app
            ./neo4j build -p neo4j_app --sha >bins/"$(./neo4j binary_name -p neo4j_app)-manifest.txt"
      # TODO: store_artifacts here if it helps debugging
      - persist_to_workspace:
          root: datashare-extension-neo4j/bins
          paths:
            - neo4j-app-*

  checkout-code:
    description: "Checkout code"
    parameters:
      revision:
        type: string
    steps:
      - run: |
          if [[ ! -d datashare-extension-neo4j ]]; then git clone git@github.com:ICIJ/datashare-extension-neo4j.git; fi 
          cd datashare-extension-neo4j
          git checkout << parameters.revision >>

  check-is-latest-commit:
    description: "Checking that no commit was made later on the same branch"
    parameters:
      branch:
        type: string
    steps:
      - run: |
          cd datashare-extension-neo4j
          git fetch
          current_commit="$(git rev-parse HEAD)"
          last_commit="$(git log -1 --pretty=%H -n 1 origin/<< parameters.branch >>)"
          if ! [[ "$current_commit" = "$last_commit" ]];then
            echo "$current_commit is not the last commit on << parameters.branch >>" && exit 1
          fi

jobs:
  build:
    executor: docker-machine
    steps:
      - checkout
      - when:
          condition:
            or:
              - matches:
                  pattern: "^release/.*$"
                  value: << pipeline.git.branch >>
              - << pipeline.git.tag >>
          steps:
            - run:
                name: Test release version
                command: ./neo4j docker_test -p release_version
      - run:
          name: Build
          command: ./neo4j docker_build

  build-darwin-universal2-binary:
    executor: darwin-universal2
    parameters:
      branch:
        type: string
    steps:
      - checkout-code:
          revision: << parameters.branch >>
      - build-binary:
          branch: << parameters.branch >>

  # We build test services to benefit from caching, using docker-compose up directly doesn't seem to benefit from it
  build-test-services:
    executor: docker-machine
    steps:
      - checkout
      - run:
          name: Build external services
          command: ./neo4j docker_build_test_services

  build-unknown-linux-binary:
    executor: unknown-linux
    parameters:
      branch:
        type: string
      resource_cls:
        type: string
    resource_class: << parameters.resource_cls >>
    steps:
      - checkout-code:
          revision: << parameters.branch >>
      - build-binary:
          branch: << parameters.branch >>

  publish-binaries:
    parameters:
      branch:
        type: string
    executor: unknown-linux
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout-code:
          revision: << parameters.branch >>
      # Try to fail early in  case another commit happened
      - check-is-latest-commit:
          branch: << parameters.branch >>
      - run:
          name: Publish assets to Github release
          command: |
            cd datashare-extension-neo4j
            tag=$(./neo4j --version)
            ls /tmp/workspace/neo4j-app-*-"$tag"* | tr '\n' '\0' | xargs -0 -I {} cp {} bins
            binaries=( $(ls bins/neo4j-app-*-$tag) )
            ./neo4j update_manifest -p neo4j_app "${binaries[@]}"
            git add src/main/resources/manifest.txt
            git commit -m "release: updating manifest.txt for $tag"
            git tag "$tag"
            git push origin "$tag"
            git push
            ./neo4j publish -p neo4j_app

  test-script:
    executor: docker-machine
    steps:
      - checkout
      - run:
          name: neo4j script tests
          command: ./neo4j docker_test -p neo4j_script

  test-java:
    executor: docker-machine
    steps:
      - checkout
      - restore_cache:
          key: v4-deps-java-{{ checksum "pom.xml" }}
      - run:
          name: Java format tests
          command: ./neo4j docker_test -p neo4j_extension_format
      - run:
          name: Java tests
          command: ./neo4j docker_test -p neo4j_extension
      - save_cache:
          key: v4-deps-java-{{ checksum "pom.xml" }}
          when: always
          paths:
            - /home/circleci/projects/datashare-extension-neo4j/.data/.m2

  test-python:
    executor: docker-machine
    steps:
      - checkout
      # On the Python side reusing the older virtualenv will speed up the build
      - restore_cache:
          key: v4-deps-python-{{ checksum "neo4j-app/poetry.lock" }}
      - run:
          name: Python format tests
          command: ./neo4j docker_test -p neo4j_app_format
      - run:
          name: Starting tests services
          command: ./neo4j start_all_test_services
      - run:
          name: Python tests
          command: ./neo4j docker_test -p neo4j_app
      - save_cache:
          key: v4-deps-python-{{ checksum "neo4j-app/poetry.lock" }}
          when: always
          paths:
            - /home/circleci/projects/datashare-extension-neo4j/.data/.cache

workflows:
  version: 2

  build_and_test:
    when:
      not: << pipeline.parameters.release_branch >>
    jobs:
      - build
      - build-test-services
      - test-script:
          requires:
            - build
      - test-java:
          requires:
            - build
      - test-python:
          requires:
            - build
            - build-test-services

  release-branch:
    when: << pipeline.parameters.release_branch >>
    jobs:
      - build-unknown-linux-binary:
          matrix:
            parameters:
              resource_cls: [ medium, arm.medium ]
              branch: [ << pipeline.parameters.branch >> ]
      - build-darwin-universal2-binary:
          branch: << pipeline.parameters.branch >>
      - publish-binaries:
          branch: << pipeline.parameters.branch >>
          requires:
            - build-unknown-linux-binary
            - build-darwin-universal2-binary
