#!/usr/bin/env bash

function _export_global_variables() {
    local root
    root="$(cd "$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")" >/dev/null && pwd)"
    source "$root"/neo4j
}

function _tests() {

    function test_is_commit_publishable() {
        _print_step "Testing _is_commit_publishable"...

        if ! _is_commit_publishable "publish: version"; then
            exit_with_message "\"publish: version\" should be publishable"
        fi

        if _is_commit_publishable "publish:"; then
            exit_with_message "\"publish:\" should not be publishable"
        fi

        if _is_commit_publishable "chore: did something"; then
            exit_with_message "\"chore: did something\" should not be publishable"
        fi
    }

    function test_update_version() {
        _print_step "Testing ./neo4j set_version"...
        # Given
        local new_version
        new_version="99999999"

        # When
        "$ROOT_DIR"/neo4j set_version $new_version

        # Then
        "$ROOT_DIR"/neo4j test -p release_version
    }

    function test_run_checksums() {
        _print_step "Testing checksums checks"...
        # Given
        local bin_path
        bin_path=$ROOT_DIR/bins/hello.txt
        echo "hello" > "$bin_path"
        new_version="99999999"

        # When
        _update_manifest "$bin_path"
        # Then
        _run_checksums || exit_with_message "Checksums failed after updating the manifest..."

        # When
        echo "tempering the binary" > "$bin_path"
        # Then
        _run_checksums && exit_with_message "Checksums succeded after tempering the binary..."
    }
}

function _main() {
    set -e
    # Export variables
    _tests
    _export_global_variables

    local test_funcs
    test_funcs=$(declare -f | sed -nr 's@^\s*function\s+(test_[a-zA-Z0-9_]+).*$@\1@p')
    for f in $test_funcs; do
        $f
    done
    echo "All tests succeeded !"
}

_main "$@"
