PROJECT_REGISTRY_DB = "datashare-project-registry"

PROJECT_RUNS_MIGRATION = "_RUNS"
PROJECT_NAME = "name"
PROJECT_NODE = "_Project"

MIGRATION_COMPLETED = "completed"
MIGRATION_LABEL = "label"
MIGRATION_NODE = "_Migration"
MIGRATION_PROJECT = "project"
MIGRATION_STARTED = "started"
MIGRATION_STATUS = "status"
MIGRATION_VERSION = "version"

TASK_NODE = "_Task"
TASK_COMPLETED_AT = "completedAt"
TASK_CREATED_AT = "createdAt"
TASK_ID = "id"
TASK_INPUTS = "inputs"
TASK_PROGRESS = "progress"
TASK_RETRIES = "retries"
TASK_TYPE = "type"

TASK_LOCK_NODE = "_TaskLock"
TASK_LOCK_TASK_ID = "taskId"
TASK_LOCK_WORKER_ID = "workerId"

TASK_ERROR_NODE = "_TaskError"
TASK_ERROR_DETAIL = "detail"
TASK_ERROR_ID = "id"
TASK_ERROR_OCCURRED_AT = "occurredAt"
TASK_ERROR_TITLE = "title"

TASK_ERROR_OCCURRED_TYPE = "_OCCURRED_DURING"

TASK_RESULT_NODE = "_TaskResult"
TASK_HAS_RESULT_TYPE = "_HAS_RESULT"
TASK_RESULT_RESULT = "result"
